# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

class TestLogout:
    def setup_method(self, method):
        # Khởi tạo trình duyệt
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.vars = {}
    
    def teardown_method(self, method):
        # Đóng trình duyệt sau khi test xong
        self.driver.quit()
    
    def test_logout(self):
        self.driver.get("https://viblo.asia/newest")
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".el-button > span"))
        ).click()
        username_field = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-input__inner"))
        )
        username_field.send_keys("QH281202")

        password_field = self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner")
        password_field.send_keys("qGV3Q5JQxEMN*Bf")
        login_button = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "span:nth-child(1)"))
        )
        login_button.click()
        avatar = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".el-popover__reference-wrapper > .avatar"))
        )
        avatar.click()
        logout_button = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.LINK_TEXT, "Đăng xuất"))
        )
        logout_button.click()
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".el-button > span"))
        )
        assert "Đăng nhập" in self.driver.page_source